version: 0
allowPullRequests: public
tasks:

  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
        branches:
          - staging
          - trying
    payload:
      maxRunTime: 3600
      image: "notriddle/docker-phoenix-elixir-test@sha256:f3b3e932d2565135ac3d1efcb52f84ba72038228a6707638b533b1a0d9025e14"
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          false # fail
    metadata:
      name: Bors-NG test suite
      description: 'Run unit and integration tests with no browser and a mock GitHub API'
      owner: 'infra@bors.tech'
      source: '{{ event.head.repo.url }}'
